void _puts_recursion(char *s);
int _putchar(char c);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int _value_recu(int n, int a);
int is_prime_number(int n);
int _value_prime(int x, int a);
int is_palindrome(char *s);
int sizestr(char *s);
int _value_palin(char *s, int a);
int wildcmp(char *s1, char *s2);
int second_val(char *s1, char *s2, int m, int k, int i, int j);
int _first_eval(char *s1, char *s2, int m);
